### ISSUE TITLE
Exclude the build-* paths from git.

### ISSUE THREAD

**Issue by denis-trofimov** [rusbiometrics/IRPV#3]
To Exclude the build-* paths from git.
```sh
$ ls
API_bin  build-IRPVTest-Desktop_Qt_5_9_0_GCC_64bit-Debug        irpv.h    nullImpl
build    build-nullimplirpv11-Desktop_Qt_5_9_0_GCC_64bit-Debug  IRPVTest  README.md
```
Folders build-IRPVTest-Desktop_Qt_5_9_0_GCC_64bit-Debug, build-nullimplirpv11-Desktop_Qt_5_9_0_GCC_64bit-Debug are generated by Qt itself and need to be omitted before commit changes to git.

**Comment by pi-null-mezon** [comment]
Я не понял в чём здесь проблема? Поясните пожалуйста

**Comment by denis-trofimov** [comment]
Folders build-IRPVTest-Desktop_Qt_5_9_0_GCC_64bit-Debug, build-nullimplirpv11-Desktop_Qt_5_9_0_GCC_64bit-Debug are generated by Qt itself and need to be omitted before commit changes to git.
