### ISSUE TITLE
Please tell how graphs are made?

### ISSUE THREAD

**Issue by denis-trofimov** [rusbiometrics/IRPV#5]
Please @pi-null-mezon tell how graphs are made?
Here https://github.com/rusbiometrics/IRPV/wiki/Example-face you have graphs but IRPVTest is probably in a best case output just a JSON file here https://github.com/rusbiometrics/IRPV/blob/7861866903a5926c92e2b18bd8905bee032cc3e3/IRPVTest/main.cpp#L362

So again the question is the data representation.

**Comment by pi-null-mezon** [comment]
Graph from wiki was generated by custom Matlab script. This script is not part of IRPV project.

**Comment by pi-null-mezon** [comment]
RBO also have GUI app named IRPVProto , that allowes to produce graphs from the json after IRPVTest. But this app is not free now.

**Comment by denis-trofimov** [comment]
Free $$$ for RBO members?

**Comment by pi-null-mezon** [comment]
It is better to ask RBO management. For the instance Danila Nikolaev <d.nikolaev@rusbiometrics.com>

**Comment by denis-trofimov** [comment]
Can close then.
